/*

 TESTMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\run\user\1000\doc\8368bc15\tilemap.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TestmapWidth 20
#define TestmapHeight 18
#define TestmapBank 0

extern unsigned char testmap[];

/* End of TESTMAP.H */
